name: Deploy on Push
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use GitHub-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          cat <<EOF > ~/.ssh/btcpricetmrw.pem
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOF
          chmod 600 ~/.ssh/btcpricetmrw.pem
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan 5.75.155.106 >> ~/.ssh/known_hosts

      - name: Run Commands via SSH
        run: |
          ssh -i ~/.ssh/btcpricetmrw.pem cristiano@5.75.155.106 "
            cd btcpricetomorrow && \
            git pull https://${{ secrets.GH_TOKEN }}@github.com/pelazas/btcpricetomorrow.git main && \
            docker-compose down --volumes --rmi all --remove-orphans && \
            docker-compose --profile production up --build -d
          "
